[profile.default]
solc = "0.8.17"
bytecode_hash = "none"
gas_reports = ["*"]
verbosity = 3
ffi = true

[profile.ci]
fuzz_runs = 10000

[rpc_endpoints]
#mainnet = "${MAINNET_RPC_URL}"
#goerli = "${GOERLI_RPC_URL}"

[etherscan]
#mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }
#goerli = { key = "${ETHERSCAN_GOERLI_KEY}" }